[package]
name = "winspaces-daemon"
version = "0.1.0"
edition = "2021"
authors = ["izantech <dev@izantech.app>"]

[[bin]]
name = "winspaces"
path = "src/main.rs"


[dependencies]
winspaces-common = { path = "../winspaces-common" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Accessibility",
    "Win32_UI_Shell",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_SystemServices",
    "Win32_System_SystemInformation",
    "Win32_System_DataExchange",
    "Win32_System_Com",
    "Win32_System_Console",
    "Win32_System_Ole",
] }

