[package]
name = "winspaces-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
winspaces-common = { path = "../winspaces-common" }
winspaces-win32 = { path = "../winspaces-win32" }
winspaces-core = { path = "../winspaces-core" }
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_UI_Accessibility",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
] }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
