[package]
name = "winspaces-common"
version = "0.1.0"
edition = "2021"
authors = ["izantech <dev@izantech.app>"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
] }
